apiVersion: v1
kind: Service
metadata:
  name: ksp-redis-game-engine-service
  labels:
    app: ksp-redis-game-engine
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
  selector:
    app: ksp-redis-game-engine

