version: "3.9"

services:

  frontend:
    build:
      context: ./services/frontend    # Dockerfile za frontend
    container_name: frontend
    ports:
      - "8000:8000"                   # host:container
    environment:
      SESSION_COOKIE_SECRET: "Ce pes psu taco moli potem tudi sam vanjo pade"
      GAME_ENGINE_URL: "http://game_engine:8001"
    depends_on:
      - game_engine

  game_engine:
    build:
      context: ./services/game_engine # Dockerfile za game_engine
    container_name: game_engine
    ports:
      - "8001:8001"                   # samo če želiš dostop direktno iz hosta
    environment:
      DB_URL: "postgresql://myuser:mypassword@db.example.com:5432/mydatabase?sslmode=require"
