insecure_bind = ["127.0.0.1:8080"]

use_reloader      = true
loglevel          = "debug"
accesslog         = "-"
errorlog          = "-"

# show remote addr, request, protocol, status, size, and time in µs
access_log_format = "%(h)s \"%(r)s\" %(H)s → %(s)s %(b)s bytes in %(D)sµs"