bind = ["127.0.0.1:4333"]
quic_bind = ["127.0.0.1:4433"]
insecure_bind = ["127.0.0.1:8080"]
certfile = "certs/fullchain.pem"
keyfile  = "certs/privkey.pem"


use_reloader      = true
loglevel          = "debug"
accesslog         = "/dev/stdout"
errorlog          = "/dev/stdout"

# show remote addr, request, protocol, status, size, and time in µs
access_log_format = "%(h)s \"%(r)s\" %(H)s → %(s)s %(b)s bytes in %(D)sµs"